---
title: "VisualizeResults"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Libraries

```{r}
library(ggplot2)
library(cowplot)
```

Center titles

```{r}
theme_update(plot.title=element_text(hjust=0.5, size=8), axis.text=element_text(size=8), axis.title=element_text(size=8))
```

Specify Prefix for filenames
```{r}
plotPath = paste(getwd(), '/plots', sep='')
prefix = "CCAAL_"
```


## Draw ScatterPlots

```{r}
plotDataColumn = function(data, column){
    title = paste("AUC of", column)
    xlabel = "SubjectNumber"
    ggplot(data, aes_q(x=~rowNumber, color=~status, y=as.name(column))) + geom_point() + ggtitle(title) + xlab(xlabel) + ylab(title)
}
```


```{r}
set.seed(42)
rows = sample(nrow(AUCResults))
# I am shuffling the rows so that the controls and SP subjects are interleaved with one another instead of appearing in separate clumps. If you want to see the data with the original subject numbers, pass in AUCResults instead of shuffledRows
shuffledRows = AUCResults[rows, ]
shuffledRows$rowNumber = 1:nrow(shuffledRows)
metrics = list( "E.local", "Cp", "Lp", "Lp.norm")
plots = lapply(metrics, plotDataColumn, data=shuffledRows)
plot_grid(plots[[1]], plots[[2]], plots[[3]], plots[[4]], ncol=2)
```

## Bar plot with errors

```{r}
longAUC = melt(AUCResults, id.vars=c("SUBJID", "status", "rowNumber", "smry_soc", "Sex", "age_at_cnb", "age_centered", "meanFD", "percentHighFD"))
groupedAUC = longAUC[,list(AUC=mean(value), stdev=sd(value)), by=list(status, variable)]
ggplot(groupedAUC, aes(x=variable, y=AUC, fill=status)) + geom_bar( stat="identity", color="black", position=position_dodge()) + geom_errorbar(aes(ymin=AUC-stdev, ymax=AUC+stdev), width=.2, position=position_dodge(0.9))
ggsave(file.path(plotPath, paste(prefix, 'BarPlots.png', sep="")))
```


## Draw Boxplots

```{r}
plotBox = function(data, column){
    title = paste("AUC of", column)
    spList = data[status=="SP"][[column]]
    controlList = data[status=="Control"][[column]]
    ggplot(data, aes_q(x=~status, y=as.name(column))) + geom_boxplot(notch=TRUE, show.legend=FALSE) +
    xlab("status") + ylab(title)
}
```


```{r}
data = covars.fmri
column = "age_at_cnb"
title = paste("AUC of", column)
spList = data[status=="SP"][[column]]
controlList = data[status=="Control"][[column]]
ggplot(data, aes_q(x=~age_at_cnb, color=~status)) + geom_histogram(fill="white", bins=10) + xlab("status") + ylab(title)
```


```{r}
metrics = list( "E.local", "Cp", "Lp", "Lp.norm")
boxes = lapply(metrics, plotBox, data=AUCResults)
plot_grid(boxes[[1]], boxes[[2]], boxes[[3]], boxes[[4]], ncol=2)
ggsave(file.path(plotPath, paste(prefix, 'BoxPlots.png', sep="")))
```

## Draw Histograms of Different Regions

```{r}
regions.dt = data.table(status=character(), anatomy=character(), network=character())
```


```{r}
region.dt = data.table(status=character(), anatomy=character(), network=character())
for (i in 1:nrow(uncorrected)){
    region.dt = rbind(region.dt, list("All SP v Control", power264[uncorrected[i]$region1Index]$Anatomy, power264[uncorrected[i]$region1Index]$network))
    region.dt = rbind(region.dt, list("All SP v Control", power264[uncorrected[i]$region2Index]$Anatomy, power264[uncorrected[i]$region2Index]$network))
}
regions.dt = rbind(regions.dt, region.dt)
```

```{r}
saveRDS(regions.dt, file=file.path(savedir, 'regions.dt.rds'), compress='xz')
```

```{r}
int_breaks <- function(x, n = 5) {
  l <- pretty(x, n)
  l[abs(l %% 1) < .Machine$double.eps ^ 0.5] 
}
```


```{r}
plotRegionBarGraph = function(data, column){
    title = column
    subset = data[status==column]
    ggplot(subset, aes(x=anatomy)) + geom_bar() + theme(axis.text.x = element_text(size=5, angle=90, hjust=1)) + ggtitle(title) + xlab("") + ylab("Number of Connections (p < .001 uncorrected)") + scale_y_continuous(breaks = int_breaks)
}
```

```{r}
plotLobesBarGraph = function(data, column){
    title = column
    subset = data[status==column]
    ggplot(subset, aes(x=lobe)) + geom_bar() + theme(axis.text.x = element_text(size=5, angle=90, hjust=1)) + ggtitle(title) + xlab("") + ylab("Number of Connections (p < .001 uncorrected)") + scale_y_continuous(breaks = int_breaks)
}
```

```{r}
comparisons = list( "All SP v Control", "Pure SP v HC", "SP + ADHD v HC", "Pure SP v SP + ADHD")
plots = lapply(comparisons, plotRegionBarGraph, data=regions.dt)
combinedPlots = plot_grid(plots[[1]], plots[[2]], plots[[3]], plots[[4]], ncol=2)
#plotRegionBarGraph(regions.dt, "All SP v Control")
plotPath = "/Users/brian/Documents/classes/quantitativepsych/rsfmri/Plots/"
ggsave(file.path(plotPath, '/Anatomy/Combined.png'))
```

```{r}
plotPath = "/Users/brian/Documents/classes/quantitativepsych/rsfmri/Plots/"
ggsave(file.path(plotPath, '/Networks/AllSPvControl.png'))
```

```{r}
plotBox(singleAUCResults, "E.nodal_Occipital_Mid.L2")
```

---

## Create adjacency matrices for Brainnet

```{r}
source("GenerateBrainnetViewer.R")
prefixPath =  paste(getwd(), '/brainnetEdges/', sep='')
groupings = c("HCvALLSP.edge", "HCvPSP.edge", "HCvADHD.edge", "ADHDvPSP.edge")
for(i in 1:length(groupings)){
  groupName = groupings[i]
  #generateBrainnetViewer(116, fcResults[[i]]$significantPValues, paste(prefixPath, 'Significant', groupName, sep=''))
  generateBrainnetViewer(116, fcResults[[i]]$uncorrected, paste(prefixPath, 'Uncorrected', groupName, sep=''))
}
```

Adjacency Matrices for Seed Results
Seed regions are L/R Amygdala, L/R dACC, L/R pCC

```{r}
source("GenerateBrainnetViewer.R")
prefixPath =  paste(getwd(), '/brainnetEdges/', sep='')
regions = c("LAmygdala", "RAmygdala", "LdACC", "RdACC", "LpCC", "RpCC");
groupings = c("HCvALLSP.edge", "HCvPSP.edge", "HCvADHD.edge", "ADHDvPSP.edge")
for(i in 1:length(groupings)){
  groupName = groupings[i]
  for(j in 1:length(regions)){
    regionName = regions[j]
    generateBrainnetViewer(116, seedResults[[j]][[i]]$significantPValues, paste(prefixPath, 'Significant', regionName, groupName, sep=''))
    generateBrainnetViewer(116, seedResults[[j]][[i]]$uncorrected, paste(prefixPath, 'Uncorrected', regionName, groupName, sep=''))
  }
}
```

