---
title: "CNNClassifier"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keras)
```

```{r}
datadir = getwd()
alldata = read.table(file=paste(datadir, "/SPvHCFCAll_data.csv", sep=''), sep=',',header = T)
status = as.factor(alldata$status)
features = alldata[, names(alldata) != "status"]

num_cols = ncol(features)
train <- array_reshape(features, c(nrow(features), num_cols, 1))
# x_test <- array_reshape(x_test, c(nrow(x_test), img_rows, img_cols, 1))
input_shape <- c(num_cols, 1)
num_classes = 2

# convert the dataframe into an array and see what happens
```


```{r}
cnn_model = keras_model_sequential() %>%
  layer_conv_1d(filters = 32, kernel_size = c(5), activation="relu", input_shape=input_shape) %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_1d(filters=64, kernel_size = c(5), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_flatten() %>% 
  layer_dense(units = 10, activation = "relu") %>% 
  layer_dropout(rate = 0.5) %>% 
  layer_dense(units = 5, activation = "relu") %>% 
  layer_dense(units = num_classes, activation = "softmax")

summary(cnn_model)
```


```{r}
nfolds=4
set.seed(21)
subdata <- createFolds(alldata$status, nfolds)

results = NULL
for (p in 1:4){
  if (p==1){
    temp1 <-subdata$Fold1
  } else if(p==2) {
    temp1 <-subdata$Fold2
  } else if(p==3) {
    temp1 <-subdata$Fold3
  } else {
    temp1 <-subdata$Fold4
  }
  
  data.rose = ROSE(status~., data=alldata[-temp1,], p=.55, hmult.majo=.25, hmult.mino=.25, seed=321)$data
  table(data.rose$status)
  
  tune.out <- tune(svm, status ~.,data=data.rose, kernel="linear", ranges=list(cost=c(0.001,0.03, 0.05, 0.1, 1)))

  summary(tune.out$best.model) 
  svmpred <- predict(tune.out$best.model, newdata=alldata[temp1,])
  table(alldata[temp1,]$status, svmpred)
  CM = confusionMatrix( svmpred, alldata[temp1,]$status, positive="SP")
  temp = c( CM$overall[1], CM$byClass[1], CM$byClass[2])
  results= rbind(results, temp) 
}

results
colMeans(results)
```

