---
title: "CNNClassifier"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keras)
```

# Using MNIST datasets

## Load datasets

```{r}
mnist <- dataset_mnist()
str(mnist)
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

# Define a few parameters to be used in the CNN model
batch_size <- 128
num_classes <- 10
epochs <- 10

# Input image dimensions
img_rows <- 28
img_cols <- 28
```

## Preprocessing

```{r}
x_train <- array_reshape(x_train, c(nrow(x_train), img_rows, img_cols, 1))
x_test <- array_reshape(x_test, c(nrow(x_test), img_rows, img_cols, 1))
input_shape <- c(img_rows, img_cols, 1)
str(x_train)
x_train <- x_train / 255
x_test <- x_test / 255
# Convert class vectors to binary class matrices
y_train <- to_categorical(y_train, num_classes)
y_test <- to_categorical(y_test, num_classes)
```
## Fitting the model

We will define a CNN with two convolutional layers, two max-pooling layers, and two dropout layers to mediate overfitting. There are three dense layers after flattening the 3D tensor. The last layer is a dense layer that connects to the response.

```{r}
cnn_model = keras_model_sequential() %>%
  layer_conv_2d(filters = 32, kernel_size = c(5, 5), activation="relu", input_shape=input_shape) %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_2d(filters=64, kernel_size = c(5,5), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_flatten() %>% 
  layer_dense(units = 120, activation = "relu") %>% 
  layer_dropout(rate = 0.5) %>% 
  layer_dense(units = 84, activation = "relu") %>% 
  layer_dense(units = num_classes, activation = "softmax")

summary(cnn_model)
```

## Compile the model

```{r}
cnn_model %>% compile(
  loss = loss_categorical_crossentropy,
  optimizer = optimizer_adadelta(),
  metrics = c('accuracy')
)

cnn_history = cnn_model %>% fit(
  x_train, y_train,
  batch_size = batch_size,
  epochs = epochs,
  validation_split = 0.2
)
```

## Evaluate Accuracy

```{r}
cnn_model %>% evaluate(x_test, y_test)
```
```{r}
str(cnn_history)
plot(cnn_history)
```

